# Generated by Django 5.2.5 on 2025-10-16 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(choices=[('Cardiología', 'Cardiología'), ('Pediatría', 'Pediatría'), ('Neurología', 'Neurología'), ('General', 'Medicina General'), ('Dermatología', 'Dermatología')], max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('diagnostico', models.CharField(max_length=255)),
                ('doctor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='records_app.doctor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
